export const GET_WORLD_CURRENT_REQUEST = 'GET_WORLD_CURRENT_REQUEST'
export const GET_WORLD_CURRENT_SUCCESS = 'GET_WORLD_CURRENT_SUCCESS'
export const GET_WORLD_CURRENT_FAIL = 'GET_WORLD_CURRENT_SUCCESS'